apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'

// Load local.properties
Properties localProperties = new Properties()
File localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    namespace("com.helpmepls.slidepuzzle")
    compileSdk 36
    defaultConfig {
        applicationId "com.helpmepls.slidepuzzle"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 20260618
        versionName "2026.06.18"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
    signingConfigs {
        release {
            storeFile file("key/keystore.jks")
            storePassword localProperties['KEYSTORE_PASSWORD']
            keyAlias localProperties['KEY_ALIAS']
            keyPassword localProperties['KEY_PASSWORD']
        }
    }
    buildFeatures {
        buildConfig = true
    }
    buildTypes {
        release {
            // nhớ kiểm tra APPLICATION_ID trong manifest
            buildConfigField "String", "ADMOB_BANNER_ID", "\"~\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"~\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"~\""

            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3940256099942544/6300978111\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3940256099942544/1033173712\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3940256099942544/9257395921\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules-debug.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.20"
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'in.srain.cube:grid-view-with-header-footer:1.0.12'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "com.google.android.material:material:1.13.0"
    implementation 'com.github.bumptech.glide:glide:5.0.5'
//    kapt 'com.github.bumptech.glide:compiler:5.0.4'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
}
