import './style.css';

// Default screenshot config
const DEFAULT_SCREENSHOTS = [
  {
    id: 1,
    file: '1_home_classic.png',
    title: 'CAPTIVATE YOUR SENSES',
    tagline: 'Solve mind-bending slide puzzles in glowing neon'
  },
  {
    id: 2,
    file: '2_settings.png',
    title: 'TAILOR YOUR COGNITION',
    tagline: 'Fine-tune haptics, reduce motion, and switch modes'
  },
  {
    id: 3,
    file: '3_home_magenta.png',
    title: 'EXPRESS YOUR STYLE',
    tagline: 'Match your mood with glowing custom neon color themes'
  },
  {
    id: 4,
    file: '4_home_time_attack.png',
    title: 'CHOOSE YOUR GRID',
    tagline: 'Configure boards from quick 3x3 to mastermind 8x8'
  },
  {
    id: 5,
    file: '5_game_5x5.png',
    title: 'BEAT THE CLOCK',
    tagline: 'Race against time in thrilling neon Time Attack mode'
  },
  {
    id: 6,
    file: '6_game_3x3.png',
    title: 'STRATEGIZE EVERY SLIDE',
    tagline: 'Optimize moves and solve before budget exhaustion'
  },
  {
    id: 7,
    file: '7_shuffle_dialog.png',
    title: 'SHUFFLE & START',
    tagline: 'Initiate randomized, fully solvable game sessions'
  },
  {
    id: 8,
    file: '8_game_shuffled.png',
    title: 'UNLEASH FLOW STATE',
    tagline: 'Focus and solve with smooth particles and ambient bloom'
  }
];

// Presets for background gradients
const GRADIENT_PRESETS = {
  cyan: {
    name: 'Cyan Cyber',
    value: 'linear-gradient(135deg, #090e1a 0%, #1e1b4b 55%, #00f2fe 100%)',
    text: '#ffffff',
    tagline: 'rgba(255,255,255,0.7)',
    dot: '#00f2fe'
  },
  magenta: {
    name: 'Neon Pink',
    value: 'linear-gradient(135deg, #090e1a 0%, #31102f 55%, #ff007f 100%)',
    text: '#ffffff',
    tagline: 'rgba(255,255,255,0.7)',
    dot: '#ff007f'
  },
  lime: {
    name: 'Cyber Lime',
    value: 'linear-gradient(135deg, #090e1a 0%, #064e3b 55%, #a6ff00 100%)',
    text: '#ffffff',
    tagline: 'rgba(255,255,255,0.7)',
    dot: '#a6ff00'
  },
  purple: {
    name: 'Purple Haze',
    value: 'linear-gradient(135deg, #090e1a 0%, #2e1065 55%, #7c3aed 100%)',
    text: '#ffffff',
    tagline: 'rgba(255,255,255,0.7)',
    dot: '#7c3aed'
  },
  void: {
    name: 'Void Minimal',
    value: 'linear-gradient(135deg, #07090f 0%, #121824 100%)',
    text: '#ffffff',
    tagline: 'rgba(255,255,255,0.6)',
    dot: '#9ca3af'
  }
};

// Editor State
let state = {
  appName: 'QUICK PUZZLE',
  appTagline: 'NEON SLIDING PUZZLE',
  deviceTarget: 'iphone', // 'iphone' or 'ipad'
  textLayout: 'top', // 'top' or 'bottom'
  themePreset: 'cyan',
  customFont: 'Outfit',
  screenshots: JSON.parse(JSON.stringify(DEFAULT_SCREENSHOTS))
};

// Initialize App
function init() {
  const appEl = document.getElementById('app');
  appEl.innerHTML = `
    <!-- Sidebar -->
    <div class="sidebar">
      <div class="sidebar-header">
        <h1>Quick Puzzle</h1>
        <p>App Store Screenshot Suite Editor</p>
      </div>
      
      <div class="sidebar-content">
        <!-- Device & Layout -->
        <div class="sidebar-section">
          <h3>Global Settings</h3>
          
          <div class="control-group">
            <label>AppName (Pre-filled)</label>
            <input type="text" id="global-app-name" class="text-input" value="${state.appName}">
          </div>
          
          <div class="control-group">
            <label>Tagline / Subtext</label>
            <input type="text" id="global-tagline" class="text-input" value="${state.appTagline}">
          </div>
          
          <div class="control-group">
            <label>Typography</label>
            <select id="select-font" class="select-input">
              <option value="Outfit" selected>Outfit (Modern)</option>
              <option value="Inter">Inter (Clean)</option>
              <option value="Space Grotesk">Space Grotesk (Tech)</option>
            </select>
          </div>

          <div class="control-group">
            <label>Text Layout</label>
            <select id="select-layout" class="select-input">
              <option value="top" selected>Text at Top</option>
              <option value="bottom">Text at Bottom</option>
            </select>
          </div>
        </div>

        <!-- Themes / Gradients -->
        <div class="sidebar-section">
          <h3>Background Theme</h3>
          <div class="theme-grid" id="theme-selectors">
            <!-- Theme buttons generated by JS -->
          </div>
        </div>
      </div>
      
      <div class="sidebar-footer">
        <button id="btn-export-all" class="btn-primary">
          <svg width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
          Export All 8 Screens
        </button>
        <button id="btn-reset" class="btn-secondary">Reset Defaults</button>
      </div>
    </div>

    <!-- Workspace Workspace -->
    <div class="workspace">
      <div class="workspace-header">
        <div class="workspace-title">
          <h2>Screenshot Workspace</h2>
          <p>Click any text overlay on a screen below to edit it inline.</p>
        </div>
        
        <div class="device-toggle">
          <button id="btn-device-iphone" class="toggle-btn active">iPhone (6.7")</button>
          <button id="btn-device-ipad" class="toggle-btn">iPad Pro (12.9")</button>
        </div>
      </div>
      
      <!-- Screens Grid -->
      <div class="screenshots-grid" id="screenshots-container">
        <!-- Cards generated by JS -->
      </div>
    </div>

    <!-- Hidden canvas for rendering and exporting -->
    <canvas id="export-helper-canvas"></canvas>
    
    <!-- Custom Toast Notification -->
    <div id="toast" class="toast">Assets exported successfully!</div>
  `;

  renderThemes();
  renderWorkspace();
  setupEventListeners();
}

// Render theme choices
function renderThemes() {
  const container = document.getElementById('theme-selectors');
  container.innerHTML = Object.entries(GRADIENT_PRESETS).map(([key, t]) => `
    <button class="theme-btn ${state.themePreset === key ? 'active' : ''}" data-theme="${key}">
      <span class="theme-color-dot" style="background-color: ${t.dot}"></span>
      ${t.name}
    </button>
  `).join('');
}

// Render screens in workspace
function renderWorkspace() {
  const container = document.getElementById('screenshots-container');
  const gradient = GRADIENT_PRESETS[state.themePreset].value;
  const isIpad = state.deviceTarget === 'ipad';
  const isBottomText = state.textLayout === 'bottom';
  
  container.innerHTML = state.screenshots.map((s) => `
    <div class="preview-card ${isIpad ? 'ipad-target' : ''} ${isBottomText ? 'text-bottom' : ''}" data-id="${s.id}">
      <!-- Gradient Background -->
      <div class="card-bg" style="background: ${gradient}"></div>
      
      <!-- Text Overlay -->
      <div class="card-text-wrapper" style="font-family: '${state.customFont}', sans-serif;">
        <input type="text" class="card-title-input" data-id="${s.id}" data-type="title" value="${s.title.toUpperCase()}">
        <input type="text" class="card-tagline-input" data-id="${s.id}" data-type="tagline" value="${s.tagline}">
      </div>
      
      <!-- Device Frame Mockup -->
      <div class="device-mockup">
        ${isIpad ? `
          <div class="ipad-frame">
            <div class="ipad-screen">
              <img class="ipad-screenshot" src="/screenshots/${s.file}" alt="App Screen">
            </div>
          </div>
        ` : `
          <div class="phone-frame">
            <div class="dynamic-island"></div>
            <div class="phone-screen">
              <img class="phone-screenshot" src="/screenshots/${s.file}" alt="App Screen">
            </div>
          </div>
        `}
      </div>
      
      <!-- Hover Actions -->
      <div class="card-actions">
        <button class="action-btn btn-export-single" data-id="${s.id}" title="Export this screen">
          <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
        </button>
      </div>
    </div>
  `).join('');

  // Re-bind inline inputs
  document.querySelectorAll('.card-title-input, .card-tagline-input').forEach(input => {
    input.addEventListener('input', (e) => {
      const id = parseInt(e.target.dataset.id);
      const type = e.target.dataset.type;
      const val = e.target.value;
      const idx = state.screenshots.findIndex(s => s.id === id);
      if (idx !== -1) {
        state.screenshots[idx][type] = val;
      }
    });
  });
}

// Show Toast
function showToast(msg) {
  const toast = document.getElementById('toast');
  toast.innerText = msg;
  toast.classList.add('show');
  setTimeout(() => {
    toast.classList.remove('show');
  }, 3000);
}

// High-fidelity Canvas Exporter
function exportToPNG(screenId, quiet = false) {
  return new Promise((resolve) => {
    const screenshot = state.screenshots.find(s => s.id === screenId);
    if (!screenshot) return resolve();

    const canvas = document.getElementById('export-helper-canvas');
    const ctx = canvas.getContext('2d');

    // App Store spec sizes
    // iPhone 6.7": 1290 x 2796
    // iPad Pro 12.9": 2048 x 2732
    const targetW = state.deviceTarget === 'ipad' ? 2048 : 1290;
    const targetH = state.deviceTarget === 'ipad' ? 2732 : 2796;
    
    canvas.width = targetW;
    canvas.height = targetH;

    // 1. Draw background gradient
    const gradientObj = GRADIENT_PRESETS[state.themePreset];
    const gr = ctx.createLinearGradient(0, 0, targetW, targetH);
    
    // Parse linear gradient colors from presets
    if (state.themePreset === 'cyan') {
      gr.addColorStop(0, '#090e1a');
      gr.addColorStop(0.55, '#1e1b4b');
      gr.addColorStop(1, '#00f2fe');
    } else if (state.themePreset === 'magenta') {
      gr.addColorStop(0, '#090e1a');
      gr.addColorStop(0.55, '#31102f');
      gr.addColorStop(1, '#ff007f');
    } else if (state.themePreset === 'lime') {
      gr.addColorStop(0, '#090e1a');
      gr.addColorStop(0.55, '#064e3b');
      gr.addColorStop(1, '#a6ff00');
    } else if (state.themePreset === 'purple') {
      gr.addColorStop(0, '#090e1a');
      gr.addColorStop(0.55, '#2e1065');
      gr.addColorStop(1, '#7c3aed');
    } else {
      gr.addColorStop(0, '#07090f');
      gr.addColorStop(1, '#121824');
    }

    ctx.fillStyle = gr;
    ctx.fillRect(0, 0, targetW, targetH);

    // 2. Load screenshot image
    const img = new Image();
    img.src = `/screenshots/${screenshot.file}`;
    img.onload = () => {
      // 3. Draw Device Mockup Bezel and screen inside
      const textAtTop = state.textLayout === 'top';
      
      // Calculate coordinates depending on device target
      let deviceW, deviceH, deviceX, deviceY, screenW, screenH, screenX, screenY, cornerR, bezelT;
      
      if (state.deviceTarget === 'ipad') {
        // iPad Spec
        deviceW = 1500;
        deviceH = 2000;
        deviceX = (targetW - deviceW) / 2;
        deviceY = textAtTop ? 580 : 160;
        
        bezelT = 24; // iPad bezel
        screenW = deviceW - bezelT * 2;
        screenH = deviceH - bezelT * 2;
        screenX = deviceX + bezelT;
        screenY = deviceY + bezelT;
        cornerR = 48;
      } else {
        // iPhone Spec
        deviceW = 900;
        deviceH = 1940;
        deviceX = (targetW - deviceW) / 2;
        deviceY = textAtTop ? 740 : 160;
        
        bezelT = 20; // iPhone bezel
        screenW = deviceW - bezelT * 2;
        screenH = deviceH - bezelT * 2;
        screenX = deviceX + bezelT;
        screenY = deviceY + bezelT;
        cornerR = 72;
      }

      // Draw device shadow
      ctx.shadowColor = 'rgba(0, 0, 0, 0.6)';
      ctx.shadowBlur = 80;
      ctx.shadowOffsetX = 0;
      ctx.shadowOffsetY = 30;

      // Draw outer device container (rounded rect)
      ctx.fillStyle = '#0e1117';
      drawRoundedRect(ctx, deviceX, deviceY, deviceW, deviceH, cornerR);
      ctx.fill();

      // Draw outer silver outline ring (very premium look)
      ctx.shadowColor = 'transparent'; // Reset shadow
      ctx.shadowBlur = 0;
      ctx.strokeStyle = '#222936';
      ctx.lineWidth = 4;
      ctx.stroke();

      // Clip screen and draw screenshot
      ctx.save();
      drawRoundedRect(ctx, screenX, screenY, screenW, screenH, cornerR - bezelT);
      ctx.clip();
      ctx.drawImage(img, screenX, screenY, screenW, screenH);
      ctx.restore();

      // Draw iPhone Dynamic Island
      if (state.deviceTarget === 'iphone') {
        ctx.fillStyle = '#000000';
        const diW = 260;
        const diH = 64;
        const diX = (targetW - diW) / 2;
        const diY = screenY + 24;
        drawRoundedRect(ctx, diX, diY, diW, diH, 32);
        ctx.fill();
      }

      // 4. Draw Typography Overlay (Titles & Taglines)
      ctx.fillStyle = '#ffffff';
      ctx.textAlign = 'center';
      
      const textYStart = textAtTop ? 220 : 2250;
      
      // Draw Title
      ctx.font = `800 ${state.deviceTarget === 'ipad' ? 100 : 84}px '${state.customFont}', sans-serif`;
      const titleText = screenshot.title.toUpperCase();
      ctx.fillText(titleText, targetW / 2, textYStart);

      // Draw Tagline
      ctx.fillStyle = 'rgba(255, 255, 255, 0.75)';
      ctx.font = `500 ${state.deviceTarget === 'ipad' ? 52 : 44}px 'Inter', sans-serif`;
      
      // Word wrap tagline helper
      const taglineText = screenshot.tagline;
      const maxTextW = targetW - 200;
      wrapText(ctx, taglineText, targetW / 2, textYStart + (state.deviceTarget === 'ipad' ? 84 : 72), 60, maxTextW);

      // 5. Download Trigger
      const dataUrl = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.download = `QuickPuzzle_${state.deviceTarget}_Screen${screenshot.id}.png`;
      link.href = dataUrl;
      link.click();
      
      if (!quiet) {
        showToast(`Screen ${screenshot.id} exported successfully!`);
      }
      resolve();
    };
  });
}

// Canvas Rounded Rectangle Helper
function drawRoundedRect(ctx, x, y, width, height, radius) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.lineTo(x + width - radius, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
  ctx.lineTo(x + width, y + height - radius);
  ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
  ctx.lineTo(x + radius, y + height);
  ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
  ctx.lineTo(x, y + radius);
  ctx.quadraticCurveTo(x, y, x + radius, y);
  ctx.closePath();
}

// Canvas Text Wrapping Helper
function wrapText(ctx, text, x, y, lineHeight, maxWidth) {
  const words = text.split(' ');
  let line = '';
  let currentY = y;

  for (let n = 0; n < words.length; n++) {
    let testLine = line + words[n] + ' ';
    let metrics = ctx.measureText(testLine);
    let testWidth = metrics.width;
    if (testWidth > maxWidth && n > 0) {
      ctx.fillText(line, x, currentY);
      line = words[n] + ' ';
      currentY += lineHeight;
    } else {
      line = testLine;
    }
  }
  ctx.fillText(line, x, currentY);
}

// Event Listeners
function setupEventListeners() {
  // Global settings changes
  document.getElementById('global-app-name').addEventListener('input', (e) => {
    state.appName = e.target.value;
    // Auto-update screens if necessary or let them remain customizable
  });
  
  document.getElementById('global-tagline').addEventListener('input', (e) => {
    state.appTagline = e.target.value;
  });

  document.getElementById('select-font').addEventListener('change', (e) => {
    state.customFont = e.target.value;
    renderWorkspace();
  });

  document.getElementById('select-layout').addEventListener('change', (e) => {
    state.textLayout = e.target.value;
    renderWorkspace();
  });

  // Device toggles
  document.getElementById('btn-device-iphone').addEventListener('click', (e) => {
    document.getElementById('btn-device-iphone').classList.add('active');
    document.getElementById('btn-device-ipad').classList.remove('active');
    state.deviceTarget = 'iphone';
    renderWorkspace();
  });

  document.getElementById('btn-device-ipad').addEventListener('click', (e) => {
    document.getElementById('btn-device-ipad').classList.add('active');
    document.getElementById('btn-device-iphone').classList.remove('active');
    state.deviceTarget = 'ipad';
    renderWorkspace();
  });

  // Background Theme Selector
  document.getElementById('theme-selectors').addEventListener('click', (e) => {
    const btn = e.target.closest('.theme-btn');
    if (btn) {
      document.querySelectorAll('.theme-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.themePreset = btn.dataset.theme;
      renderWorkspace();
    }
  });

  // Single card download action
  document.getElementById('screenshots-container').addEventListener('click', (e) => {
    const btn = e.target.closest('.btn-export-single');
    if (btn) {
      e.stopPropagation();
      const id = parseInt(btn.dataset.id);
      exportToPNG(id);
    }
  });

  // Export all screens
  document.getElementById('btn-export-all').addEventListener('click', async () => {
    showToast("Starting batch download, please allow multi-file downloads in browser...");
    for (let s of state.screenshots) {
      await exportToPNG(s.id, true);
      // Small pause to prevent browser blocking sequential downloads
      await new Promise(r => setTimeout(r, 400));
    }
    showToast("All 8 screens downloaded!");
  });

  // Reset defaults
  document.getElementById('btn-reset').addEventListener('click', () => {
    state.screenshots = JSON.parse(JSON.stringify(DEFAULT_SCREENSHOTS));
    state.themePreset = 'cyan';
    state.customFont = 'Outfit';
    state.textLayout = 'top';
    document.getElementById('select-font').value = 'Outfit';
    document.getElementById('select-layout').value = 'top';
    renderThemes();
    renderWorkspace();
    showToast("Reset to default layout!");
  });
}

// Boot Editor
document.addEventListener('DOMContentLoaded', init);
